name: Test setup

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check secret exists
        run: |
          if [ -z "$PLAY_PUBLISHER_JSON" ]; then
            echo "PLAY_PUBLISHER_JSON is empty"
            exit 1
          else
            echo "Secret length: ${#PLAY_PUBLISHER_JSON}"
          fi
        env:
          PLAY_PUBLISHER_JSON: ${{ secrets.PLAY_PUBLISHER_JSON }}

      - name: Gradle help
        run: ./gradlew tasks --no-daemon
