name: Release to Google Play

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create Play credentials file
        run: echo "$PLAY_PUBLISHER_JSON" > play-credentials.json
        env:
          PLAY_PUBLISHER_JSON: ${{ secrets.PLAY_PUBLISHER_JSON }}

      - name: Build release bundle
        run: ./gradlew :app:bundleRelease

      - name: Publish to Play (internal track)
        run: |
          ./gradlew :app:publishReleaseBundle \
            -Pplay.serviceAccountCredentials=play-credentials.json \
            -Pplay.track=internal \
            -Pplay.releaseStatus=completed

      - name: Upload AAB as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/*.aab
